apiVersion: v1
kind: Pod
metadata:
   name: helloworld
   namespace: dev
spec:
   containers:
   - name: helloworld-container01
     image: nehashirsat/helloworld:$BUILD_NUMBER
     ports:
     - containerPort: 9000
